# Generated by Django 5.2.6 on 2026-03-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Prix d'achat en GNF (pour calcul du bénéfice)", max_digits=12, verbose_name="Prix d'achat"),
        ),
        migrations.AddField(
            model_name='product',
            name='seuil_alerte_stock',
            field=models.IntegerField(default=3, help_text='Alerte si le stock descend en dessous de ce seuil', verbose_name='Seuil alerte stock'),
        ),
        migrations.CreateModel(
            name='OfflineSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_vente', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix de vente unitaire')),
                ('prix_achat', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Prix d'achat unitaire")),
                ('canal', models.CharField(choices=[('boutique', 'Boutique physique'), ('whatsapp', 'WhatsApp'), ('telephone', 'Téléphone'), ('autre', 'Autre')], default='boutique', max_length=20, verbose_name='Canal de vente')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('telephone_client', models.CharField(blank=True, max_length=20, verbose_name='Téléphone client')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_offline', to='boutique.product')),
            ],
            options={
                'verbose_name': 'Vente hors site',
                'verbose_name_plural': 'Ventes hors site',
                'ordering': ['-date_vente'],
            },
        ),
    ]
