# Generated by Django 5.2.6 on 2026-03-13 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_product_prix_achat_product_seuil_alerte_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=14)),
                ('categorie', models.CharField(choices=[('achat_stock', 'Achat de stock'), ('transport', 'Transport / Livraison'), ('loyer', 'Loyer'), ('salaire', 'Salaire'), ('marketing', 'Marketing / Publicité'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la dépense')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('motif', models.CharField(choices=[('achat', 'Achat / Réapprovisionnement'), ('vente_en_ligne', 'Vente en ligne'), ('vente_hors_site', 'Vente hors site'), ('retour', 'Retour client'), ('ajustement', 'Ajustement manuel'), ('perte', 'Perte / Casse')], default='ajustement', max_length=20)),
                ('quantite', models.IntegerField()),
                ('stock_avant', models.IntegerField()),
                ('stock_apres', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='Référence commande, vente hors-site, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='boutique.product')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
